services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '9000:9000'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/auth/.env

  stores:
    build:
      context: .
      dockerfile: ./apps/stores/Dockerfile
      target: development
    command: pnpm run start:dev stores
    ports:
      - '9002:9002'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/stores/.env

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: micro
      MYSQL_USER: desha
      MYSQL_PASSWORD: desha
    ports:
      - '3306:3306'
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672


  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    ports:
      - '9009:9009'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/gateway/.env